# m2.toml - mxpkg package manifest (self-hosting)
name=mxpkg
version=0.1.1
entry=src/Main.mod
edition=m2plus
includes=src

[deps]
m2sys=path:../../libs/m2sys
m2http=path:../../libs/m2http
m2auth=path:../../libs/m2auth

[cc]

[cc.feature.MACOS]
cflags=-I/opt/homebrew/opt/openssl@3/include
ldflags=-L/opt/homebrew/opt/openssl@3/lib
