name=gfx_demo
version=0.1.0
entry=src/GfxDemo.mod
m2plus=false
includes=src ../../libs/m2gfx/src

[deps]

[cc]
cflags=-I/opt/homebrew/include
ldflags=-L/opt/homebrew/lib
libs=SDL2 SDL2_ttf
extra-c=../../libs/m2gfx/src/gfx_bridge.c
