[release]
compiler = "1.7.0"
date = "2026-03-30"

[tools]
mxpkg0 = "0.1.1"
mxpkg = "0.1.1"
vscode-m2plus = "0.2.0"

[libraries]
m2alloc = "1.1.0"
m2auth = "0.1.0"
m2bytes = "1.2.0"
m2cli = "0.1.1"
m2conf = "0.1.0"
m2evloop = "0.2.0"
m2fmt = "0.1.1"
m2fsm = "1.0.0"
m2futures = "0.2.0"
m2gfx = "0.5.0"
m2glob = "0.1.0"
m2hash = "0.1.1"
m2http = "0.1.3"
m2http2 = "0.1.1"
m2http2server = "0.2.0"
m2json = "0.2.0"
m2lmdb = "0.2.0"
m2log = "1.1.0"
m2metrics = "0.1.0"
m2oidc = "0.1.3"
m2path = "0.1.0"
m2pthreads = "0.1.1"
m2regex = "0.1.1"
m2rpc = "0.1.2"
m2sockets = "0.1.0"
m2sqlite = "0.1.0"
m2stdlib = "0.1.0"
m2stream = "0.2.0"
m2sys = "0.2.0"
m2text = "0.1.1"
m2tls = "0.1.1"
m2tok = "0.1.1"
m2ws = "0.1.2"
m2zlib = "0.1.0"
