IMPLEMENTATION MODULE Lockfile;

FROM SYSTEM IMPORT ADR;
FROM Strings IMPORT Assign, Length, Concat, CompareStr, Pos, Copy;
FROM InOut IMPORT WriteString, WriteLn;
FROM Sys IMPORT m2sys_fopen, m2sys_fclose, m2sys_fread_line, m2sys_fwrite_str,
               m2sys_file_exists, m2sys_sha256_file, m2sys_sha256_str,
               m2sys_list_dir, m2sys_exec_output, m2sys_join_path;
FROM Manifest IMPORT GetName, GetVersion, DepCount, GetDepName, GetDepPath,
                     GetIncludes, GetEntry;

CONST
  MaxLockDeps = 64;

VAR
  lDepNames: ARRAY [0..MaxLockDeps-1] OF ARRAY [0..63] OF CHAR;
  lDepVersions: ARRAY [0..MaxLockDeps-1] OF ARRAY [0..31] OF CHAR;
  lDepSources: ARRAY [0..MaxLockDeps-1] OF ARRAY [0..15] OF CHAR;
  lDepShas: ARRAY [0..MaxLockDeps-1] OF ARRAY [0..64] OF CHAR;
  lDepPaths: ARRAY [0..MaxLockDeps-1] OF ARRAY [0..511] OF CHAR;
  lDepURLs: ARRAY [0..MaxLockDeps-1] OF ARRAY [0..511] OF CHAR;
  lDepCount: INTEGER;
  tmp: ARRAY [0..1023] OF CHAR;

PROCEDURE Exists(path: ARRAY OF CHAR): INTEGER;
BEGIN
  RETURN m2sys_file_exists(ADR(path))
END Exists;

PROCEDURE Read(path: ARRAY OF CHAR);
VAR fh, n, eqPos, vlen, curDep: INTEGER;
    rmode: ARRAY [0..1] OF CHAR;
    line: ARRAY [0..511] OF CHAR;
    key: ARRAY [0..63] OF CHAR;
    value: ARRAY [0..255] OF CHAR;
    section: ARRAY [0..15] OF CHAR;
BEGIN
  lDepCount := 0;
  curDep := -1;
  Assign("r", rmode);
  fh := m2sys_fopen(ADR(path), ADR(rmode));
  IF fh < 0 THEN
    WriteString("mxpkg: cannot open "); WriteString(path); WriteLn;
    RAISE LockfileError
  END;
  TRY
    Assign("", section);
    LOOP
      n := m2sys_fread_line(fh, ADR(line), 512);
      IF n < 0 THEN EXIT END;
      IF Length(line) = 0 THEN
        (* skip blank *)
      ELSIF line[0] = '#' THEN
        (* skip comment *)
      ELSIF line[0] = '[' THEN
        IF Pos("dep.", line) < Length(line) THEN
          (* Extract dep name from [dep.NAME] *)
          Assign("dep", section);
          IF lDepCount < MaxLockDeps THEN
            curDep := lDepCount;
            INC(lDepCount);
            (* Parse name from [dep.NAME] *)
            n := Pos(".", line);
            IF n < Length(line) THEN
              vlen := Length(line) - n - 2; (* skip ']' *)
              IF vlen > 0 THEN
                Copy(line, n + 1, vlen, lDepNames[curDep])
              END
            END;
            lDepVersions[curDep][0] := 0C;
            lDepSources[curDep][0] := 0C;
            lDepShas[curDep][0] := 0C;
            lDepPaths[curDep][0] := 0C;
            lDepURLs[curDep][0] := 0C
          END
        ELSIF Pos("package", line) < Length(line) THEN
          Assign("pkg", section);
          curDep := -1
        ELSIF Pos("toolchain", line) < Length(line) THEN
          Assign("tc", section);
          curDep := -1
        ELSE
          Assign("other", section);
          curDep := -1
        END
      ELSE
        (* Parse key=value *)
        eqPos := Pos("=", line);
        IF eqPos < Length(line) THEN
          Copy(line, 0, eqPos, key);
          vlen := Length(line) - eqPos - 1;
          IF vlen > 0 THEN
            Copy(line, eqPos + 1, vlen, value)
          ELSE
            value[0] := 0C
          END;
          IF (curDep >= 0) AND (CompareStr(section, "dep") = 0) THEN
            IF CompareStr(key, "version") = 0 THEN
              Assign(value, lDepVersions[curDep])
            ELSIF CompareStr(key, "source") = 0 THEN
              Assign(value, lDepSources[curDep])
            ELSIF CompareStr(key, "sha256") = 0 THEN
              Assign(value, lDepShas[curDep])
            ELSIF CompareStr(key, "path") = 0 THEN
              Assign(value, lDepPaths[curDep])
            ELSIF CompareStr(key, "url") = 0 THEN
              Assign(value, lDepURLs[curDep])
            END
          END
        END
      END
    END
  FINALLY
    n := m2sys_fclose(fh)
  END
END Read;

PROCEDURE WrLine(fh: INTEGER; s: ARRAY OF CHAR);
VAR nl: ARRAY [0..1] OF CHAR;
    rc: INTEGER;
BEGIN
  rc := m2sys_fwrite_str(fh, ADR(s));
  nl[0] := 12C; nl[1] := 0C;
  rc := m2sys_fwrite_str(fh, ADR(nl))
END WrLine;

PROCEDURE Write(path: ARRAY OF CHAR);
VAR
  fh, rc, i, nd: INTEGER;
  wmode: ARRAY [0..1] OF CHAR;
  ln: ARRAY [0..511] OF CHAR;
  name: ARRAY [0..63] OF CHAR;
  ver: ARRAY [0..31] OF CHAR;
  dname: ARRAY [0..63] OF CHAR;
  dpath: ARRAY [0..255] OF CHAR;
  t: ARRAY [0..511] OF CHAR;
BEGIN
  Assign("w", wmode);
  fh := m2sys_fopen(ADR(path), ADR(wmode));
  IF fh < 0 THEN
    WriteString("mxpkg: cannot create "); WriteString(path); WriteLn;
    RAISE LockfileError
  END;
  TRY
    WrLine(fh, "# m2.lock - generated by mxpkg resolve");
    WrLine(fh, "");
    WrLine(fh, "[package]");

    GetName(name);
    Assign("name=", ln); Concat(ln, name, t); Assign(t, ln);
    WrLine(fh, ln);

    GetVersion(ver);
    Assign("version=", ln); Concat(ln, ver, t); Assign(t, ln);
    WrLine(fh, ln);

    nd := DepCount();
    IF nd > 0 THEN
      WrLine(fh, "");
      i := 0;
      WHILE i < nd DO
        GetDepName(i, dname);
        GetDepPath(i, dpath);
        Assign("[dep.", ln);
        Concat(ln, dname, t); Assign(t, ln);
        Concat(ln, "]", t); Assign(t, ln);
        WrLine(fh, ln);
        Assign("path=", ln);
        Concat(ln, dpath, t); Assign(t, ln);
        WrLine(fh, ln);
        INC(i)
      END
    END
  FINALLY
    rc := m2sys_fclose(fh)
  END
END Write;

PROCEDURE WriteEnhanced(path: ARRAY OF CHAR);
VAR
  fh, rc, i: INTEGER;
  wmode: ARRAY [0..1] OF CHAR;
  ln: ARRAY [0..511] OF CHAR;
  name: ARRAY [0..63] OF CHAR;
  ver: ARRAY [0..31] OF CHAR;
  t: ARRAY [0..511] OF CHAR;
BEGIN
  Assign("w", wmode);
  fh := m2sys_fopen(ADR(path), ADR(wmode));
  IF fh < 0 THEN
    WriteString("mxpkg: cannot create "); WriteString(path); WriteLn;
    RAISE LockfileError
  END;
  TRY
    WrLine(fh, "# m2.lock - generated by mxpkg resolve");
    WrLine(fh, "");
    WrLine(fh, "[package]");

    GetName(name);
    Assign("name=", ln); Concat(ln, name, t); Assign(t, ln);
    WrLine(fh, ln);

    GetVersion(ver);
    Assign("version=", ln); Concat(ln, ver, t); Assign(t, ln);
    WrLine(fh, ln);

    IF lDepCount > 0 THEN
      i := 0;
      WHILE i < lDepCount DO
        WrLine(fh, "");
        Assign("[dep.", ln);
        Concat(ln, lDepNames[i], t); Assign(t, ln);
        Concat(ln, "]", t); Assign(t, ln);
        WrLine(fh, ln);

        IF Length(lDepVersions[i]) > 0 THEN
          Assign("version=", ln);
          Concat(ln, lDepVersions[i], t); Assign(t, ln);
          WrLine(fh, ln)
        END;

        IF Length(lDepSources[i]) > 0 THEN
          Assign("source=", ln);
          Concat(ln, lDepSources[i], t); Assign(t, ln);
          WrLine(fh, ln)
        END;

        IF Length(lDepShas[i]) > 0 THEN
          Assign("sha256=", ln);
          Concat(ln, lDepShas[i], t); Assign(t, ln);
          WrLine(fh, ln)
        END;

        IF Length(lDepPaths[i]) > 0 THEN
          Assign("path=", ln);
          Concat(ln, lDepPaths[i], t); Assign(t, ln);
          WrLine(fh, ln)
        END;

        IF Length(lDepURLs[i]) > 0 THEN
          Assign("url=", ln);
          Concat(ln, lDepURLs[i], t); Assign(t, ln);
          WrLine(fh, ln)
        END;

        INC(i)
      END
    END
  FINALLY
    rc := m2sys_fclose(fh)
  END
END WriteEnhanced;

PROCEDURE LockDepCount(): INTEGER;
BEGIN RETURN lDepCount END LockDepCount;

PROCEDURE GetDepResolvedPath(i: INTEGER; VAR buf: ARRAY OF CHAR);
BEGIN
  IF (i >= 0) AND (i < lDepCount) THEN
    Assign(lDepPaths[i], buf)
  ELSE
    buf[0] := 0C
  END
END GetDepResolvedPath;

PROCEDURE GetDepSha(i: INTEGER; VAR buf: ARRAY OF CHAR);
BEGIN
  IF (i >= 0) AND (i < lDepCount) THEN
    Assign(lDepShas[i], buf)
  ELSE
    buf[0] := 0C
  END
END GetDepSha;

PROCEDURE GetDepSource(i: INTEGER; VAR buf: ARRAY OF CHAR);
BEGIN
  IF (i >= 0) AND (i < lDepCount) THEN
    Assign(lDepSources[i], buf)
  ELSE
    buf[0] := 0C
  END
END GetDepSource;

PROCEDURE GetDepLockVersion(i: INTEGER; VAR buf: ARRAY OF CHAR);
BEGIN
  IF (i >= 0) AND (i < lDepCount) THEN
    Assign(lDepVersions[i], buf)
  ELSE
    buf[0] := 0C
  END
END GetDepLockVersion;

PROCEDURE GetDepLockName(i: INTEGER; VAR buf: ARRAY OF CHAR);
BEGIN
  IF (i >= 0) AND (i < lDepCount) THEN
    Assign(lDepNames[i], buf)
  ELSE
    buf[0] := 0C
  END
END GetDepLockName;

PROCEDURE SetDepEntry(i: INTEGER; name: ARRAY OF CHAR; version: ARRAY OF CHAR;
                      source: ARRAY OF CHAR; sha: ARRAY OF CHAR;
                      path: ARRAY OF CHAR);
BEGIN
  IF (i >= 0) AND (i < MaxLockDeps) THEN
    Assign(name, lDepNames[i]);
    Assign(version, lDepVersions[i]);
    Assign(source, lDepSources[i]);
    Assign(sha, lDepShas[i]);
    Assign(path, lDepPaths[i])
  END
END SetDepEntry;

PROCEDURE SetLockDepCount(n: INTEGER);
BEGIN
  IF n <= MaxLockDeps THEN
    lDepCount := n
  END
END SetLockDepCount;

PROCEDURE SetDepURL(i: INTEGER; url: ARRAY OF CHAR);
BEGIN
  IF (i >= 0) AND (i < MaxLockDeps) THEN
    Assign(url, lDepURLs[i])
  END
END SetDepURL;

PROCEDURE GetDepURL(i: INTEGER; VAR buf: ARRAY OF CHAR);
BEGIN
  IF (i >= 0) AND (i < lDepCount) THEN
    Assign(lDepURLs[i], buf)
  ELSE
    buf[0] := 0C
  END
END GetDepURL;

(* --- bootstrap.lock support --- *)

PROCEDURE ComputeTreeHash(VAR hashOut: ARRAY OF CHAR);
VAR
  entry: ARRAY [0..255] OF CHAR;
  incl: ARRAY [0..1023] OF CHAR;
  listing: ARRAY [0..4095] OF CHAR;
  filePath: ARRAY [0..511] OF CHAR;
  fileSha: ARRAY [0..64] OF CHAR;
  concatBuf: ARRAY [0..8191] OF CHAR;
  tpos, tlen, sp, ci, fi, rc: INTEGER;
  fname: ARRAY [0..255] OF CHAR;
  t: ARRAY [0..1023] OF CHAR;
BEGIN
  hashOut[0] := 0C;
  concatBuf[0] := 0C;
  ci := 0;

  (* List source files from includes dirs *)
  GetIncludes(incl);
  IF Length(incl) = 0 THEN
    Assign("src", incl)
  END;

  (* Process each include dir *)
  tpos := 0;
  tlen := Length(incl);
  WHILE tpos < tlen DO
    WHILE (tpos < tlen) AND (incl[tpos] = ' ') DO INC(tpos) END;
    sp := tpos;
    WHILE (sp < tlen) AND (incl[sp] # ' ') DO INC(sp) END;
    IF sp > tpos THEN
      fi := 0;
      WHILE tpos < sp DO
        fname[fi] := incl[tpos];
        INC(fi); INC(tpos)
      END;
      fname[fi] := 0C;

      rc := m2sys_list_dir(ADR(fname), ADR(listing), 4096);
      IF rc > 0 THEN
        (* Process each file in listing (newline-separated) *)
        tpos := 0;
        (* Note: reusing tpos within inner loop is fine since we break *)
        fi := 0;
        WHILE fi <= rc DO
          IF (fi = rc) OR (listing[fi] = 12C) THEN
            IF fi > tpos THEN
              (* Extract filename *)
              sp := 0;
              WHILE tpos < fi DO
                filePath[sp] := listing[tpos];
                INC(sp); INC(tpos)
              END;
              filePath[sp] := 0C;

              (* Check if .mod or .def *)
              IF (Pos(".mod", filePath) < Length(filePath)) OR
                 (Pos(".def", filePath) < Length(filePath)) THEN
                (* Build full path *)
                m2sys_join_path(ADR(fname), ADR(filePath), ADR(t), 1024);
                rc := m2sys_sha256_file(ADR(t), ADR(fileSha));
                IF rc = 0 THEN
                  (* Append "filename:sha256\n" to concatBuf *)
                  sp := 0;
                  WHILE (filePath[sp] # 0C) AND (ci < 8190) DO
                    concatBuf[ci] := filePath[sp];
                    INC(ci); INC(sp)
                  END;
                  IF ci < 8190 THEN
                    concatBuf[ci] := ':'; INC(ci)
                  END;
                  sp := 0;
                  WHILE (fileSha[sp] # 0C) AND (ci < 8190) DO
                    concatBuf[ci] := fileSha[sp];
                    INC(ci); INC(sp)
                  END;
                  IF ci < 8190 THEN
                    concatBuf[ci] := 12C; INC(ci)
                  END
                END
              END
            END;
            tpos := fi + 1
          END;
          INC(fi)
        END
      END
    END;
    IF tpos < tlen THEN INC(tpos) END
  END;

  concatBuf[ci] := 0C;
  IF ci > 0 THEN
    m2sys_sha256_str(ADR(concatBuf), ci, ADR(hashOut))
  END
END ComputeTreeHash;

PROCEDURE WriteBoot(path: ARRAY OF CHAR);
VAR
  fh, rc, i: INTEGER;
  wmode: ARRAY [0..1] OF CHAR;
  ln: ARRAY [0..511] OF CHAR;
  name: ARRAY [0..63] OF CHAR;
  ver: ARRAY [0..31] OF CHAR;
  entry: ARRAY [0..255] OF CHAR;
  entrySha: ARRAY [0..64] OF CHAR;
  treeSha: ARRAY [0..64] OF CHAR;
  vjson: ARRAY [0..1023] OF CHAR;
  m2cVer: ARRAY [0..31] OF CHAR;
  m2cTarget: ARRAY [0..63] OF CHAR;
  t: ARRAY [0..511] OF CHAR;
BEGIN
  Assign("w", wmode);
  fh := m2sys_fopen(ADR(path), ADR(wmode));
  IF fh < 0 THEN
    WriteString("mxpkg: cannot create "); WriteString(path); WriteLn;
    RAISE LockfileError
  END;
  TRY
    WrLine(fh, "# bootstrap.lock - generated by mxpkg lock");
    WrLine(fh, "");

    (* [toolchain] *)
    WrLine(fh, "[toolchain]");
    (* Get m2c version via --version-json *)
    Assign("m2c --version-json", ln);
    rc := m2sys_exec_output(ADR(ln), ADR(vjson), 1024);
    (* Parse version from JSON - simple extraction *)
    m2cVer[0] := 0C;
    m2cTarget[0] := 0C;
    IF rc = 0 THEN
      (* Extract version: find "version":" *)
      i := Pos("version", vjson);
      IF i < Length(vjson) THEN
        (* Skip to value *)
        i := i + 10; (* past version":" *)
        rc := 0;
        WHILE (i < Length(vjson)) AND (vjson[i] # '"') DO
          m2cVer[rc] := vjson[i];
          INC(rc); INC(i)
        END;
        m2cVer[rc] := 0C
      END;
      (* Extract target *)
      i := Pos("target", vjson);
      IF i < Length(vjson) THEN
        i := i + 9; (* past target":" *)
        rc := 0;
        WHILE (i < Length(vjson)) AND (vjson[i] # '"') DO
          m2cTarget[rc] := vjson[i];
          INC(rc); INC(i)
        END;
        m2cTarget[rc] := 0C
      END
    END;
    Assign("m2c_version=", ln); Concat(ln, m2cVer, t); Assign(t, ln);
    WrLine(fh, ln);
    Assign("m2c_target=", ln); Concat(ln, m2cTarget, t); Assign(t, ln);
    WrLine(fh, ln);

    WrLine(fh, "");

    (* [package] *)
    WrLine(fh, "[package]");
    GetName(name);
    Assign("name=", ln); Concat(ln, name, t); Assign(t, ln);
    WrLine(fh, ln);

    GetVersion(ver);
    Assign("version=", ln); Concat(ln, ver, t); Assign(t, ln);
    WrLine(fh, ln);

    (* Entry sha256 *)
    GetEntry(entry);
    IF Length(entry) > 0 THEN
      rc := m2sys_sha256_file(ADR(entry), ADR(entrySha));
      IF rc = 0 THEN
        Assign("entry_sha256=", ln); Concat(ln, entrySha, t); Assign(t, ln);
        WrLine(fh, ln)
      END
    END;

    (* Tree sha256 *)
    ComputeTreeHash(treeSha);
    IF Length(treeSha) > 0 THEN
      Assign("tree_sha256=", ln); Concat(ln, treeSha, t); Assign(t, ln);
      WrLine(fh, ln)
    END;

    (* Dep entries from current lockfile state *)
    IF lDepCount > 0 THEN
      i := 0;
      WHILE i < lDepCount DO
        WrLine(fh, "");
        Assign("[dep.", ln);
        Concat(ln, lDepNames[i], t); Assign(t, ln);
        Concat(ln, "]", t); Assign(t, ln);
        WrLine(fh, ln);

        IF Length(lDepVersions[i]) > 0 THEN
          Assign("version=", ln);
          Concat(ln, lDepVersions[i], t); Assign(t, ln);
          WrLine(fh, ln)
        END;

        IF Length(lDepShas[i]) > 0 THEN
          Assign("sha256=", ln);
          Concat(ln, lDepShas[i], t); Assign(t, ln);
          WrLine(fh, ln)
        END;

        IF Length(lDepSources[i]) > 0 THEN
          Assign("source=", ln);
          Concat(ln, lDepSources[i], t); Assign(t, ln);
          WrLine(fh, ln)
        END;

        INC(i)
      END
    END
  FINALLY
    rc := m2sys_fclose(fh)
  END
END WriteBoot;

PROCEDURE VerifyBoot(path: ARRAY OF CHAR);
VAR
  fh, n, eqPos, vlen, errors: INTEGER;
  rmode: ARRAY [0..1] OF CHAR;
  line: ARRAY [0..511] OF CHAR;
  key: ARRAY [0..63] OF CHAR;
  value: ARRAY [0..255] OF CHAR;
  storedEntry: ARRAY [0..64] OF CHAR;
  storedTree: ARRAY [0..64] OF CHAR;
  actualEntry: ARRAY [0..64] OF CHAR;
  actualTree: ARRAY [0..64] OF CHAR;
  entry: ARRAY [0..255] OF CHAR;
  rc: INTEGER;
BEGIN
  errors := 0;
  storedEntry[0] := 0C;
  storedTree[0] := 0C;

  Assign("r", rmode);
  fh := m2sys_fopen(ADR(path), ADR(rmode));
  IF fh < 0 THEN
    WriteString("mxpkg: cannot read "); WriteString(path); WriteLn;
    RAISE LockfileError
  END;
  TRY
    LOOP
      n := m2sys_fread_line(fh, ADR(line), 512);
      IF n < 0 THEN EXIT END;
      eqPos := Pos("=", line);
      IF eqPos < Length(line) THEN
        Copy(line, 0, eqPos, key);
        vlen := Length(line) - eqPos - 1;
        IF vlen > 0 THEN
          Copy(line, eqPos + 1, vlen, value)
        ELSE
          value[0] := 0C
        END;
        IF CompareStr(key, "entry_sha256") = 0 THEN
          Assign(value, storedEntry)
        ELSIF CompareStr(key, "tree_sha256") = 0 THEN
          Assign(value, storedTree)
        END
      END
    END
  FINALLY
    n := m2sys_fclose(fh)
  END;

  (* Verify entry hash *)
  GetEntry(entry);
  IF Length(entry) > 0 THEN
    IF Length(storedEntry) > 0 THEN
      rc := m2sys_sha256_file(ADR(entry), ADR(actualEntry));
      IF rc = 0 THEN
        IF CompareStr(storedEntry, actualEntry) # 0 THEN
          WriteString("mxpkg: entry hash mismatch"); WriteLn;
          WriteString("  expected: "); WriteString(storedEntry); WriteLn;
          WriteString("  actual:   "); WriteString(actualEntry); WriteLn;
          INC(errors)
        END
      ELSE
        WriteString("mxpkg: failed to hash entry file"); WriteLn;
        INC(errors)
      END
    END
  END;

  (* Verify tree hash *)
  IF Length(storedTree) > 0 THEN
    ComputeTreeHash(actualTree);
    IF CompareStr(storedTree, actualTree) # 0 THEN
      WriteString("mxpkg: tree hash mismatch"); WriteLn;
      WriteString("  expected: "); WriteString(storedTree); WriteLn;
      WriteString("  actual:   "); WriteString(actualTree); WriteLn;
      INC(errors)
    END
  END;

  IF errors = 0 THEN
    WriteString("mxpkg verify: OK"); WriteLn
  ELSE
    WriteString("mxpkg verify: FAILED"); WriteLn;
    RAISE LockfileError
  END
END VerifyBoot;

END Lockfile.
