name=dpaint
version=0.1.0
entry=src/DPaint.mod
m2plus=true
includes=src ../../libs/m2gfx/src

[deps]

[cc]
libs=SDL2 SDL2_ttf
extra-c=../../libs/m2gfx/src/gfx_bridge.c

[cc.feature.MACOS]
cflags=-I/opt/homebrew/include
ldflags=-L/opt/homebrew/lib
